title: Hacker theme
description: Hacker is a theme for GitHub Pages.
show_downloads: true
google_analytics:
plausible:
# plausible_script_url: https://plausible.io/js/script.js  # Optional: for self-hosted Plausible instances
theme: jekyll-theme-hacker